// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvRteLUZ5zEhm7j1HjwF1hsSKSNYZ6v_Y',
    appId: '1:773169716410:web:31855918e65acf53e43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    authDomain: 'beachbook-163923.firebaseapp.com',
    storageBucket: 'beachbook-163923.appspot.com',
    measurementId: 'G-CR7ZEVY3ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtWFj4LQ4wSOVrLGU8b6nl41QnycgxnM',
    appId: '1:773169716410:android:a9c6f15619722f2ce43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    storageBucket: 'beachbook-163923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwRIewWfdUMUlvVzikrknXih_cba4f7X0',
    appId: '1:773169716410:ios:24a78062ff4e9d82e43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    storageBucket: 'beachbook-163923.appspot.com',
    androidClientId: '773169716410-htfg2qot9tqknt135te02nsv7aracbvt.apps.googleusercontent.com',
    iosClientId: '773169716410-i8vsog2ngvg6bprr48naed46mtkafq5t.apps.googleusercontent.com',
    iosBundleId: 'com.ziehro.beachbookLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwRIewWfdUMUlvVzikrknXih_cba4f7X0',
    appId: '1:773169716410:ios:b9eb5d30a53b0e7ee43683',
    messagingSenderId: '773169716410',
    projectId: 'beachbook-163923',
    storageBucket: 'beachbook-163923.appspot.com',
    androidClientId: '773169716410-htfg2qot9tqknt135te02nsv7aracbvt.apps.googleusercontent.com',
    iosClientId: '773169716410-4pebc9acnvg6cd0eg95fb7krh4auskas.apps.googleusercontent.com',
    iosBundleId: 'com.ziehro.beachbookLocator.RunnerTests',
  );
}
